### Send mail
POST http://localhost:8080/api/email
Content-Type: application/json

{
  "to": "rodolfo.okino@gmail.com",
  "subject": "test subject",
  "body": "test email body"
}

### Send mail test validation
POST http://localhost:8080/api/email
Content-Type: application/json

{
  "to": "",
  "subject": "",
  "body": ""
}
